[package]
name = "way-cooler-background"
version = "0.1.0"
authors = ["Timidger <APragmaticPlace@gmail.com>"]

[dependencies]
wayland-sys = { version = "^0.6.0", features = ["client", "dlopen"] }
wayland-client = { version = "^0.6.0", features = ["cursor", "dlopen"] }
gdk-pixbuf = "0.1.0"
tempfile = "2.1"
byteorder = ">= 0.3, < 0.6"
rustwlc = "0.5"
cairo-rs = {version = "^0", features = ["png"] }#{ git = "https://github.com/gtk-rs/cairo" } #"^0"
gdk-sys = "0.3.1"
memmap = "0.5"

[dependencies.gtk]
version = "0.1.0"
features = ["v3_16"]

# To make this work, gotta compile against the git version, because I'm grabbing gdk-sys not from git...

[replace]
"glib-sys:0.3.1" = { git = "https://github.com/gtk-rs/sys" }
"gobject-sys:0.3.1" = { git = "https://github.com/gtk-rs/sys" }
"cairo-sys-rs:0.3.1" = { git = "https://github.com/gtk-rs/cairo" }
